import Link from 'next/link'
import Footer from '../components/Footer'

export const metadata = {
  title: 'Privacy Policy',
  description: 'How we handle your data.',
}

export default function PrivacyPolicyPage() {
  return (
    <div className="bg-white text-black flex flex-col min-h-screen">
      {/* Navbar */}
      <div className="flex justify-between items-start p-8">
        <Link href="/" className="text-2xl font-bold hover:opacity-70 transition-opacity">
          ALLVITR
        </Link>
        <Link href="/contact" className="text-xl hover:underline">
          Contact
        </Link>
      </div>

      {/* Main Content */}
      <main className="flex-1 px-8 pb-12 max-w-4xl w-full">
        <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
        <p className="text-gray-600 mb-8">Last updated: August 31, 2025</p>
        
        <div className="space-y-8 text-black leading-relaxed">
        <p>
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <section>
          <h2 className="text-3xl font-bold mb-4 text-black">Definitions</h2>
          
          <div className="space-y-4">
            <p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
            
            <p><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
            
            <p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Allvitr AS (legal entity name, street address, postal code and city), Norway.</p>
            
            <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
            
            <p><strong>Country</strong> refers to: Norway</p>
            
            <p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
            
            <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
            
            <p><strong>Service</strong> refers to the Website.</p>
            
            <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
            
            <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, basic security logs).</p>
            
            <p><strong>Website</strong> refers to Allvitr, accessible from https://www.allvitr.no/</p>
            
            <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
          </div>
        </section>

        <section>
          <h2 className="text-3xl font-bold mb-4 text-black">Collecting and Using Your Personal Data</h2>
          
          <h3 className="text-2xl font-semibold mb-3 text-black mt-6">Types of Data Collected</h3>
          
          <h4 className="text-xl font-semibold mb-2 text-black mt-4">Personal Data</h4>
          <p className="mb-4">
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>Email address</li>
            <li>First name and last name (optional)</li>
            <li>Authentication data (e.g., password hash), account status</li>
          </ul>
          
          <h4 className="text-xl font-semibold mb-2 text-black mt-6">Usage Data</h4>
          <p className="mb-4">
            Usage Data is collected automatically when using the Service and is kept minimal for security and reliability.
          </p>
          <p>
            Usage Data may include information such as IP address, timestamps of logins, failed login attempts, and technical identifiers (e.g. session or authentication tokens). We do not collect behavioral analytics for marketing purposes.
          </p>
        </section>

        <section>
          <h3 className="text-2xl font-semibold mb-3 text-black mt-6">Tracking Technologies and Cookies</h3>
          <p>
            We do not use Cookies or similar client-side tracking technologies on our Website. The Service functions without placing Cookies on Your Device. We also do not use analytics or advertising pixels. We maintain minimal server-side logs for security and reliability purposes as described under Usage Data.
          </p>
        </section>

        <section>
          <h3 className="text-2xl font-semibold mb-3 text-black mt-6">Use of Your Personal Data</h3>
          <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>To provide and maintain our Service, including to secure accounts and ensure availability.</li>
            <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
            <li>For the performance of a contract: providing the Service You have requested and related support.</li>
            <li>To contact You: service-related communications (e.g., security, critical updates). We do not send marketing without your consent.</li>
            <li>To manage Your requests: to receive and handle support requests.</li>
            <li>For business transfers: in case of a merger, acquisition or asset sale, where user data may be part of the transferred assets.</li>
            <li>For other purposes: such as aggregate service quality monitoring and improving security.</li>
          </ul>
          
          <p className="mt-4 mb-4">We may share Your personal information in the following situations:</p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>With Service Providers: e.g., hosting, email delivery, and support tools acting on Our behalf.</li>
            <li>For business transfers: during negotiations or completion of a merger, sale of assets, financing, or acquisition.</li>
            <li>With Affiliates: if applicable, subject to this Privacy Policy.</li>
            <li>With Your consent: for any other purpose with Your consent.</li>
          </ul>
        </section>

        <section>
          <h3 className="text-2xl font-semibold mb-3 text-black mt-6">Retention of Your Personal Data</h3>
          <p>
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We retain authentication records and basic security logs for a limited period that is appropriate for security, troubleshooting, and compliance, unless a longer retention period is required by law.
          </p>
        </section>

        <section>
          <h3 className="text-2xl font-semibold mb-3 text-black mt-6">Transfer of Your Personal Data</h3>
          <p>
            Your information may be processed in locations where Our Service Providers operate. When transferring Personal Data outside the EEA, We use appropriate safeguards (such as the EU Standard Contractual Clauses and additional measures where necessary) to protect Your information.
          </p>
        </section>

        <section>
          <h3 className="text-2xl font-semibold mb-3 text-black mt-6">Delete Your Personal Data</h3>
          <p>
            You have the right to delete or request that We assist in deleting Personal Data that We have collected about You. Where applicable, You may delete certain information from within the Service (account settings). You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us. We may retain certain information where We have a legal obligation or legitimate basis to do so.
          </p>
        </section>

        <section>
          <h2 className="text-3xl font-bold mb-4 text-black mt-8">Disclosure of Your Personal Data</h2>
          
          <h3 className="text-2xl font-semibold mb-3 text-black mt-6">Business Transactions</h3>
          <p>
            If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
          </p>
          
          <h3 className="text-2xl font-semibold mb-3 text-black mt-6">Law enforcement</h3>
          <p>
            Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
          </p>
          
          <h3 className="text-2xl font-semibold mb-3 text-black mt-6">Other legal requirements</h3>
          <p className="mb-4">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>
        </section>

        <section>
          <h2 className="text-3xl font-bold mb-4 text-black mt-8">Security of Your Personal Data</h2>
          <p>
            The security of Your Personal Data is important to Us. While no method of transmission over the Internet or electronic storage is 100% secure, We apply appropriate technical and organizational measures to protect Your Personal Data.
          </p>
        </section>

        <section>
          <h2 className="text-3xl font-bold mb-4 text-black mt-8">Children&apos;s Privacy</h2>
          <p>
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under 13 without verification of parental consent, We will take steps to remove that information.
          </p>
        </section>

        <section>
          <h2 className="text-3xl font-bold mb-4 mt-8">Links to Other Websites</h2>
          <p>
            Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services.
          </p>
        </section>

        <section>
          <h2 className="text-3xl font-bold mb-4 mt-8">Changes to this Privacy Policy</h2>
          <p>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the &quot;Last updated&quot; date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes are effective when they are posted on this page.
          </p>
        </section>

        <section>
          <h2 className="text-3xl font-bold mb-4 mt-8">Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy, You can contact by email: <a href="mailto:privacy@allvitr.com" className="text-blue-600 hover:text-blue-800 underline">privacy@allvitr.com</a>
          </p>
        </section>
      </div>
      </main>
      
      <Footer />
    </div>
  )
}
